/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import {HTMLStencilElement, JSXBase} from '@stencil/core/internal';


export namespace Components {
    interface MapComponent {
        'apiKey': string;
        'cluster': boolean;
        'fitLocations': boolean;
        'locations': Array<Location>;
    }
}

declare global {


    interface HTMLMapComponentElement extends Components.MapComponent, HTMLStencilElement {
    }

    var HTMLMapComponentElement: {
        prototype: HTMLMapComponentElement;
        new(): HTMLMapComponentElement;
    };

    interface HTMLElementTagNameMap {
        'map-component': HTMLMapComponentElement;
    }
}

declare namespace LocalJSX {
    interface MapComponent extends JSXBase.HTMLAttributes<HTMLMapComponentElement> {
        'apiKey'?: string;
        'cluster'?: boolean;
        'fitLocations'?: boolean;
        'locations'?: Array<Location>;
    }

    interface IntrinsicElements {
        'map-component': MapComponent;
    }
}

export {LocalJSX as JSX};


declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements extends LocalJSX.IntrinsicElements {
        }
    }
}


